version: '3.3'

x-build: &build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      VERSION: "2.0.0"

services:
  firm_demo1:
    <<: *build
    volumes:
    - type: bind
      source: ./settings/settings_client_a.ini
      target: /settings.ini
    - type: bind
      source: ./data/sample_data1.csv
      target: /data.csv
    - type: bind
      source: ./result
      target: /result
    - type: bind
      source: ./.logs/firm_demo1
      target: /.logs
    command:
      - /bin/bash
      - '-c'
      - ./mapping settings.ini data.csv result/result1.csv 5

  firm_demo2:
    <<: *build
    volumes:
    - type: bind
      source: ./settings/settings_client_b.ini
      target: /settings.ini
    - type: bind
      source: ./data/sample_data2.csv
      target: /data.csv
    - type: bind
      source: ./result
      target: /result
    - type: bind
      source: ./.logs/firm_demo2
      target: /.logs
    command:
      - /bin/bash
      - '-c'
      - ./mapping settings.ini data.csv result/result2.csv 5
