version: '3.3'

x-build: &build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      VERSION: "0.1.1"

services:
  firm_demo1:
    <<: *build
    volumes:
    - type: bind
      source: ./settings/settings_firm_a.ini
      target: /settings.ini
    - type: bind
      source: ./data/sample_data1.csv
      target: /data.csv
    - type: bind
      source: ./result
      target: /result
    command:
      - /bin/bash
      - '-c'
      - ./cross_app_bin settings.ini data.csv result/result1.csv 5

  firm_demo2:
    <<: *build
    volumes:
    - type: bind
      source: ./settings/settings_firm_b.ini
      target: /settings.ini
    - type: bind
      source: ./data/sample_data2.csv
      target: /data.csv
    - type: bind
      source: ./result
      target: /result
    command:
      - /bin/bash
      - '-c'
      - ./cross_app_bin settings.ini data.csv result/result2.csv 5
